### PR TITLE
Variant rework

### LINKED ISSUE #199: Creating swatch option without value breaks products
**Describe the bug**
When I created a new colour without any value, products page with the new attribute was broken (blank page was shown) 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a new colour swatch (https://docs.magento.com/m2/ce/user_guide/catalog/swatch-create.html)
2. Make sure the swatch does not have colour 
3. Make sure the new colour is added to a product 
4. Go to the product page 
5. Notice a blank page

**Expected behaviour**
Adding a swatch without any value should not break product page.

**Additional context**
Perhaps, the issue might be in filter as it contains all the colours, because some of the products without the selected attribute value also break.

### LINKED ISSUE #211: When opening a configurable product, attributes are preselected already
**Describe the bug**
When I open a configurable product, a simple product with preselected attributes shows up. 

**To Reproduce**
1. Go to a configurable product page
2. **Notice the attributes are already preselected** 

**Expected behavior**
No attributes should be selected when I open a configurable product

### LINKED ISSUE #229: Add to cart button breaks on PLP
**Describe the bug**
When a simple product is added to cart from PLP, the `ADD TO CART` button does not stop loading even though the product has been already added. 

**To Reproduce**
1. Go to PLP 
2. Add a simple product to cart from the PLP
3. **Notice the button loading** 

**Expected behavior**
After a product is added to cart, the `ADD TO CART` button should stop loading.

### LINKED ISSUE #249: Configurable products are shown as simple under related products on PDP
**Describe the bug**
When a configurable product is added as related to a particular product, on PDP the configurable product is shown as simple. A customer does not need to configure it first but can add to cart straight away. 

**To Reproduce**
1. In the admin view, select edit a product 
2. Add a configurable product as related to it.
3. Go to PDP of the edited product 
4. **Notice the text described above**

**Expected behavior**
If a configurable product is added as related, a customer cannot add it to cart straight away from PDP, it should be configured first.

### PR DESCRIPTION
**Pull request by xapiksw**
- Reworked PLP and PDP to support url parameters instead of variants
- Reworked PDP to support unpreselected parameters
- Modified Cart to support described changes

fixes #229
fixes #249
fixes #211
fixes #199

### CODE REVIEW

**Comment by xapiksw** [comment]
Related PR for the backend: https://github.com/scandipwa/route717/pull/5

File: src/app/route/CategoryPage/CategoryPage.component.js [hunk 1]
```diff
@@ -104,7 +104,10 @@ class CategoryPage extends Component {
 
         const totalPages = Math.ceil(totalItems / pageSize);
         const currentPage = parseInt(totalPages < pageFromUrl ? totalPages : pageFromUrl, 10);
-        const productsLoaded = Object.values(pages).reduce((accumulator, page) => accumulator + page.length, 0);
+
+        const pagesValues = Object.values(pages);
+        const productsLoaded = pagesValues.length
+            ? pagesValues.reduce((accumulator, page) => accumulator + page.length, 0) : 0;
```
Comment (alfredsgenkins) [inline src/app/route/CategoryPage/CategoryPage.component.js]: Optimise this into:

```js
const productsLoaded = pagesValues.reduce((accumulator, page) => accumulator + page.length, 0);
```

Because reduce returns its initial value if array length is 0.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 2]
```diff
@@ -22,18 +22,23 @@ import ProductActions from 'Component/ProductActions';
 import GroupedProductsList from 'Component/GroupedProductsList';
 import Meta from 'Component/Meta';
 import { ProductType } from 'Type/ProductList';
-import { getUrlParam, getQueryParam, updateQueryParamWithoutHistory } from 'Util/Url';
+import { getVariantIndex } from 'Util/Product';
 import RelatedProducts from 'Component/RelatedProducts';
+import {
+    getUrlParam, convertQueryStringToKeyValuePairs, updateQueryParamWithoutHistory
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Let's brake `{}` imports into new line each, if more than 2. Linter config pending.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 3]
```diff
@@ -43,27 +48,39 @@ class ProductPage extends Component {
...
+                variants, configurable_options, id, type_id
+            },
+            location: { search }
+        } = props;
+
+        if (!(configurable_options && variants && id !== stateId)) return null;
+
+        const parameters = Object.entries(convertQueryStringToKeyValuePairs(search))
+            .reduce((acc, [key, value]) => {
+                if (configurable_options.find(({ attribute_code }) => attribute_code === key)) {
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Find returns `configurable_option`, it is wrong function to use here. 

```js
Object.entries(convertQueryStringToKeyValuePairs(search)).reduce((acc, [key, value]) => (
    configurable_options.some(({ attribute_code }) => attribute_code === key)) ? { ...acc, [key]: value } : acc
), {});
```

File: src/app/route/ProductPage/ProductPage.component.js [hunk 4]
```diff
@@ -43,27 +48,39 @@ class ProductPage extends Component {
...
+                    return { ...acc, [key]: value };
+                }
+                return acc;
+            }, {});
+
+        const configurableVariantIndex = getVariantIndex(variants, parameters);
+
+        if (Object.keys(parameters).length === Object.keys(configurable_options).length
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Let's agree to use following structure of complex ifs:

```js
if (
    Object.keys(parameters).length === Object.keys(configurable_options).length
    || type_id !== 'configurable'
) {
    return { id, parameters, configurableVariantIndex };
}
```

Comment (alfredsgenkins) [reply src/app/route/ProductPage/ProductPage.component.js]: Why not, btw `return { id, parameters, configurableVariantIndex };` always, regarding of this check? Just makes sure it returns undefined or some non integer value from `getVariantIndex` function.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 5]
```diff
@@ -43,27 +48,39 @@ class ProductPage extends Component {
...
+        }
 
-        return (locationState && Object.hasOwnProperty.call(locationState, 'variantIndex'))
-            ? locationState.variantIndex
-            : null;
+        return { id, parameters };
     }
 
     componentDidUpdate(prevProps) {
         const { location } = this.props;
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Destruct both `prevProps` and `this.props` to `pathname`, make sure it is named `pathname` and `prevPathname`.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 6]
```diff
@@ -109,40 +109,41 @@ class ProductPage extends Component {
...
+
     getConfigurableVariantMediaLibrary() {
         const { product: { variants } } = this.props;
-        const { configurableVariantIndex } = this.state;
         const dataSource = this.getDataSource();
+        const index = this.getConfigurableVariantIndex(variants);
+
         const { media_gallery_entries } = dataSource;
-        const { media_gallery_entries: configurableMediaGallery } = variants[configurableVariantIndex].product;
+        const { media_gallery_entries: configurableMediaGallery } = variants[index].product;
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Destruct including `product`.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 7]
```diff
@@ -109,40 +109,41 @@ class ProductPage extends Component {
...
      */
-    getThumbnail(currentVariantIndex, dataSource) {
+    getThumbnail(dataSource) {
         const { thumbnail, variants } = dataSource;
+        const index = this.getConfigurableVariantIndex(variants);
+
         const variantThumbnail = variants
-            && variants[ currentVariantIndex ]
-            && variants[ currentVariantIndex ].product.thumbnail;
+            && variants[ index ]
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: No need for spaces around `[]`.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 8]
```diff
@@ -109,40 +109,41 @@ class ProductPage extends Component {
...
     }
 
     /**
      * Get thumbnail picture of the product
-     * @param {Number} currentVariantIndex product variant index
      * @param {Object} dataSource product data
      * @return {Number} variant index
      */
-    getThumbnail(currentVariantIndex, dataSource) {
+    getThumbnail(dataSource) {
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Write this function like this:

```js
getThumbnail(dataSource) {
    const index = this.getConfigurableVariantIndex(variants);
    const { thumbnail, variants = { product: {} } } = dataSource;
    const { product: { thumbnail: variantThumbnail } } = variants;
    return variantThumbnail || thumbnail;
}
```

File: src/app/route/ProductPage/ProductPage.component.js [hunk 9]
```diff
@@ -172,24 +172,36 @@ class ProductPage extends Component {
...
-    updateUrl(variant) {
-        const { configurableVariantIndex } = this.state;
+    updateUrl(key, value) {
+        const { product: { variants, configurable_options } } = this.props;
+        const { configurableVariantIndex, parameters: oldParameters } = this.state;
 
-        if (configurableVariantIndex !== variant) updateQueryParamWithoutHistory('variant', variant);
+        const parameters = {
+            ...oldParameters,
+            [key]: `${value}`
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Is this `toString()` conversion? I would prefer `.toString()` or I would try `value` directly, as it is URL => logically a string. Please check.

File: src/app/route/ProductPage/ProductPage.component.js [hunk 10]
```diff
@@ -172,24 +172,36 @@ class ProductPage extends Component {
...
+        };
 
-        return this.setState({ configurableVariantIndex: variant });
+        this.setState({ parameters });
+        updateQueryParamWithoutHistory(key, value);
+
+        const newIndex = getVariantIndex(variants, parameters);
+        if (Object.keys(parameters).length === Object.keys(configurable_options).length
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Why is this check needed here? Could not we check for `configurableVariantIndex !== newIndex` only?

File: src/app/store/Cart/Cart.reducer.js [hunk 11]
```diff
@@ -31,9 +32,26 @@ const updateCartTotals = (action) => {
 
 const updateAllProductsInCart = (action) => {
     const { products } = action;
+    const parameteredProducts = Object.keys(products).reduce((accum, key) => {
+        const currentItem = products[key];
+        if (currentItem.type_id !== 'simple') {
+            const { variants, configurable_options, configurableVariantIndex } = currentItem;
```
Comment (alfredsgenkins) [inline src/app/store/Cart/Cart.reducer.js]: Move this one line above, include `type_id` to destruction.

File: src/app/store/Cart/Cart.reducer.js [hunk 12]
```diff
@@ -31,9 +32,26 @@ const updateCartTotals = (action) => {
...
+            const selectedVariant = variants[configurableVariantIndex].product;
```
Comment (alfredsgenkins) [inline src/app/store/Cart/Cart.reducer.js]: Use it like this:

```js
const { product: selectedVariant } = variants[configurableVariantIndex];
```

File: src/app/store/Cart/Cart.reducer.js [hunk 13]
```diff
@@ -31,9 +32,26 @@ const updateCartTotals = (action) => {
...
+            const required_params = configurable_options.map(({ attribute_code }) => attribute_code);
+            const parameters = generateParameters(selectedVariant.attributes, required_params);
+            Object.assign(selectedVariant, { parameters });
+        }
+
+        return {
+            ...accum,
+            [key]: {
+                ...currentItem
```
Comment (alfredsgenkins) [inline src/app/store/Cart/Cart.reducer.js]: Why not `[key]: currentItem` ?

File: src/app/store/Cart/Cart.reducer.js [hunk 14]
```diff
@@ -31,9 +32,26 @@ const updateCartTotals = (action) => {
...
 const updateAllProductsInCart = (action) => {
     const { products } = action;
+    const parameteredProducts = Object.keys(products).reduce((accum, key) => {
+        const currentItem = products[key];
+        if (currentItem.type_id !== 'simple') {
+            const { variants, configurable_options, configurableVariantIndex } = currentItem;
+            const selectedVariant = variants[configurableVariantIndex].product;
+            const required_params = configurable_options.map(({ attribute_code }) => attribute_code);
+            const parameters = generateParameters(selectedVariant.attributes, required_params);
+            Object.assign(selectedVariant, { parameters });
```
Comment (alfredsgenkins) [inline src/app/store/Cart/Cart.reducer.js]: I would instead do `variants[configurableVariantIndex].product = { ... selectedVariant, parameters }`. Because otherwise it violates functional programming paradigm.

Comment (alfredsgenkins) [reply src/app/store/Cart/Cart.reducer.js]: Could you also explain necessity of this operation?

File: src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js [hunk 15]
```diff
@@ -23,13 +23,7 @@ const CmsBlocksAndSliderReducer = (state = initialState, action) => {
...
     case UPDATE_CMS_BLOCKS:
         const { blocks: { items: blockItems } } = action;
-        const items = blockItems.reduce((o, item) => {
-            if (item) {
-                return { ...o, [item.identifier]: item };
-            }
-
-            return { ...o };
-        }, {});
+        const items = blockItems.reduce((o, item) => ({ ...o, [item.identifier]: item }), {});
```
Comment (alfredsgenkins) [inline src/app/store/CmsBlocksAndSlider/CmsBlocksAndSlider.reducer.js]: Finally someone did it :D

File: src/app/store/Product/Product.reducer.js [hunk 16]
```diff
@@ -23,26 +24,33 @@ const initialState = {
 const ProductReducer = (state = initialState, action) => {
     switch (action.type) {
     case UPDATE_PRODUCT_DETAILS:
-        const { product, product: { attributes, variants }, filters } = action;
+        const {
+            product,
+            product: {
+                variants: initialVariants, configurable_options, attributes, type_id
```
Comment (alfredsgenkins) [inline src/app/store/Product/Product.reducer.js]: Let's put them on separate lines.

File: src/app/store/Product/Product.reducer.js [hunk 17]
```diff
@@ -23,26 +24,33 @@ const initialState = {
...
+            }
+        } = action;
+
+        const brand = getBrand(attributes);
```
Comment (alfredsgenkins) [inline src/app/store/Product/Product.reducer.js]: No no no no no, please no specific attributes selections, we are not a custom store, we are an abstract theme for everyone.

File: src/app/store/Product/Product.reducer.js [hunk 18]
```diff
@@ -23,26 +24,33 @@ const initialState = {
...
 
-        attributes.forEach(({ attribute_code, attribute_value }) => {
-            product[attribute_code] = attribute_value;
-        });
+        const parameters = !initialVariants
+            ? attributes.reduce(
+                (acc, { attribute_code, attribute_value }) => ({ ...acc, [attribute_code]: attribute_value }),
+                {}
+            ) : undefined;
```
Comment (alfredsgenkins) [inline src/app/store/Product/Product.reducer.js]: Please do not do `undefined` to variable that is clearly an empty object. Write this reduce like this:

```js
attributes.reduce((acc, { attribute_code, attribute_value }) => (
    { ...acc, [attribute_code]: attribute_value }
), {});
```

File: src/app/store/ProductList/ProductList.reducer.js [hunk 19]
```diff
@@ -23,28 +24,26 @@ const initialState = {
...
 
-            if (variants) {
-                variants.forEach(({ product: { attributes } }, j) => {
-                    if (attributes) {
-                        attributes.forEach(({ attribute_code, attribute_value }) => {
-                            items[i].variants[j].product[attribute_code] = attribute_value;
-                        });
-                    }
-                });
+        const brand = getBrand(attributes);
```
Comment (alfredsgenkins) [inline src/app/store/ProductList/ProductList.reducer.js]: Replace this one, please.

File: src/app/store/ProductList/ProductList.reducer.js [hunk 20]
```diff
@@ -23,28 +24,26 @@ const initialState = {
...
+        const variants = initialVariants ? getVariantsWithParams(initialVariants, configurable_options) : undefined;
```
Comment (alfredsgenkins) [inline src/app/store/ProductList/ProductList.reducer.js]: Please stop setting undefined variables. They must not change their type.

File: src/app/store/RelatedProducts/RelatedProducts.reducer.js [hunk 21]
```diff
@@ -22,19 +22,27 @@ const initialState = {
...
+            const brand = getBrand(attributes);
 
-        if (products.items) {
-            products.items.forEach(({ attributes }, i) => {
-                attributes.forEach(({ attribute_code, attribute_value }) => {
-                    products.items[i][attribute_code] = attribute_value;
-                });
-            });
-        }
+            return [
```
Comment (alfredsgenkins) [inline src/app/store/RelatedProducts/RelatedProducts.reducer.js]: Write this in single line, please.

File: src/app/util/Product/Product.js [hunk 22]
```diff
@@ -0,0 +1,91 @@
...
+
+/**
+ * Get product's brand from attributes
+ * @param {{ attribute_value: string, attribute_code: string }} attributes
+ * @returns {string}
+ */
+export const getBrand = (attributes) => {
+    const { attribute_value } = attributes.find(({ attribute_code }) => attribute_code === 'brand');
+    return attribute_value;
+};
```
Comment (alfredsgenkins) [inline src/app/util/Product/Product.js]: I have no idea why you did this.

File: src/app/util/Product/index.js [hunk 23]
```diff
@@ -0,0 +1,12 @@
...
+ *
+ * Copyright © Scandiweb, Inc. All rights reserved.
+ * See LICENSE for license details.
+ *
+ * @license OSL-3.0 (Open Software License ("OSL") v. 3.0)
+ * @package scandipwa/base-theme
+ * @link https://github.com/scandipwa/base-theme
+ */
+
+export * from './Product';
```
Comment (alfredsgenkins) [inline src/app/util/Product/index.js]: Please do it for all suitable places.

File: src/app/component/ProductActions/ProductActions.component.js [hunk 24]
```diff
@@ -291,7 +260,7 @@ class ProductActions extends Component {
             if (attributes.length) {
                 return attributes.map((attribute) => {
                     const { attribute_code } = attribute;
-                    if (product[attribute_code]) {
+                    if (parameters && parameters[attribute_code]) {
```
[the remark this answers is not in the document]
Comment (xapiksw) [reply src/app/component/ProductActions/ProductActions.component.js]: Parameters are made from `configurable_options`.

File: src/app/component/CartItem/CartItem.component.js [hunk 25]
```diff
@@ -88,9 +96,7 @@ class CartItem extends Component {
     handleRemoveItem() {
         const { removeProduct, product } = this.props;
         this.setState({ isLoading: true });
-        removeProduct({ product }).then(
-            () => this.setState({ isLoading: false })
-        );
+        removeProduct({ product });
```
[the remark this answers is not in the document]
Comment (xapiksw) [reply src/app/component/CartItem/CartItem.component.js]: Not inifinite loader, but we cannot set it to false in `.then` clause because after item deletion, component does not exist, so the only thing it causes is memory-leaking.

File: src/app/route/ProductPage/ProductPage.component.js (hunk 10 above)
Comment (dmitrijs-voronovs) [reply src/app/route/ProductPage/ProductPage.component.js]: Without `(Object.keys(parameters).length === Object.keys(configurable_options).length` check, AddToCart button becomes enabled when there is only one parameter selected and user switches it to another parameter of the same type (e.g. no color & size 34 -> size 36)

File: src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js [hunk 26]
```diff
@@ -107,47 +138,45 @@ class CategoryShoppingOptions extends Component {
...
-                </li>
-            );
-        });
-    }
-
     renderCustomFilters() {
-        const { availableFilters } = this.props;
+        const { availableFilters, customFiltersValues } = this.props;
+
+        const configurable_options = availableFilters.reduce((co, item) => {
```
Comment (xapiksw) [inline src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js]: Any ideas about this one?

File: src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js [hunk 27]
```diff
@@ -29,27 +29,25 @@ class CategoryShoppingOptions extends Component {
...
+     * @param {String} value
+     * @returns {Object[]}
+     * @memberof CategoryShoppingOptions
      */
-    toggleCustomFilter(requestVar, value) {
-        const { updateFilter, customFiltersValues } = this.props;
-        const newFilterArray = customFiltersValues[requestVar] ? customFiltersValues[requestVar] : [];
+    getNewFilterArray(filterKey, value) {
+        const { customFiltersValues } = this.props;
+        const newFilterArray = Array.from(customFiltersValues[filterKey] || []);
```
Comment (xapiksw) [inline src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js]: Even if it looks better, it is less optimized than ```javascript
const newFilterArray = customFilersValues[filterKey] !== undefinded ? Array.from(customFilersValues[filterKey]) : [];
`

**Comment by xapiksw** [comment]
Fixes #249 
Fixes #211 
Fixes #199

File: src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js [hunk 28]
```diff
@@ -29,27 +30,25 @@ class CategoryShoppingOptions extends Component {
...
```
Comment (xapiksw) [inline src/app/component/CategoryShoppingOptions/CategoryShoppingOptions.component.js]: I believe
```javascript
const newFilterArray = filterKey in customFiltersValues ? Array.from(customFiltersValues[filterKey]) : [];
```
is more optimized.

File: src/app/component/ProductCard/ProductCard.component.js [hunk 29]
```diff
@@ -35,25 +37,36 @@ class ProductCard extends Component {
...
 
-                const isCorrectVariant = Object.keys(customFilters).every(filterKey => (
-                    customFilters[ filterKey ].find(value => +value === +product[ filterKey ])
-                ));
+        const indexes = getVariantsIndexes(variants, customFilters);
+        const [index] = indexes;
 
-                if (isCorrectVariant) return i;
-            }
+        if (!variants[index]) return { indexes: [], parameters: {} };
```
Comment (alfredsgenkins) [inline src/app/component/ProductCard/ProductCard.component.js]: You could merge `filterKeys.length < 0` and `!variants[index]` checks together? It will appear more logical.
However in terms of performance your solution is better. You can leave current.

File: src/app/component/ProductCard/ProductCard.component.js [hunk 30]
```diff
@@ -62,9 +75,11 @@ class ProductCard extends Component {
      * @return {void}
      */
     getThumbnail(currentVariantIndex) {
-        const { product: { thumbnail, variants } } = this.props;
-        const variantThumbnail = variants ? variants[ currentVariantIndex ].product.thumbnail.path : null;
-        return variantThumbnail || (thumbnail && thumbnail.path);
+        const { product: { thumbnail = {}, variants = [] } } = this.props;
+
+        const { path } = thumbnail;
```
Comment (alfredsgenkins) [inline src/app/component/ProductCard/ProductCard.component.js]: You can do: `product: { thumbnail: { path } = {}`

File: src/app/component/ProductCard/ProductCard.component.js [hunk 31]
```diff
@@ -116,12 +121,24 @@ class ProductCard extends Component {
...
               removeWishlistItem
+              configurableVariantIndex={ index }
+            />
+        );
+    }
+
+    renderAddToWishlistButton(notReady) {
+        const { product } = this.props;
+        if (notReady) return <TextPlaceholder length="medium" />;
+        return (
```
Comment (alfredsgenkins) [inline src/app/component/ProductCard/ProductCard.component.js]: Let's put enter here, to separate multi-line return.

File: src/app/component/ProductCard/ProductCard.component.js [hunk 32]
```diff
@@ -149,30 +166,22 @@ class ProductCard extends Component {
...
+                attributes = {}
             },
             product,
             arePlaceholdersShown,
             mix
         } = this.props;
 
-        const variantIndex = this.getCurrentVariantIndex();
-        const thumbnail = this.getThumbnail(variantIndex);
+        const { brand = {} } = attributes;
```
Comment (alfredsgenkins) [inline src/app/component/ProductCard/ProductCard.component.js]: Go for `{ brand: { attribute_value: brand } = {} }`

File: src/app/route/ProductPage/ProductPage.component.js [hunk 33]
```diff
@@ -43,27 +53,37 @@ class ProductPage extends Component {
...
+
+        const parameters = Object.entries(convertQueryStringToKeyValuePairs(search))
+            .reduce((acc, [key, value]) => {
+                if (key in configurable_options) {
+                    return { ...acc, [key]: value };
+                }
+                return acc;
+            }, {});
+
+        if (Object.keys(parameters).length !== Object.keys(configurable_options).length) return { id, parameters };
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: For long strings, let's move `return { id, parameters };` to next line in curly brackets :)

File: src/app/route/ProductPage/ProductPage.component.js [hunk 34]
```diff
@@ -172,24 +181,55 @@ class ProductPage extends Component {
...
+            ...oldParameters,
+            [key]: value.toString(10)
+        };
 
-        return this.setState({ configurableVariantIndex: variant });
+        this.setState({ parameters });
+        updateQueryParamWithoutHistory(key, value);
+
+        const newIndex = getVariantIndex(variants, parameters);
+        if (
```
Comment (alfredsgenkins) [inline src/app/route/ProductPage/ProductPage.component.js]: Enter here, because if is multi-line

File: src/app/component/OptionsPlaceholder/OptionsPlaceholder.component.js [hunk 35]
```diff
@@ -0,0 +1,38 @@
...
+import React, { Component } from 'react';
+import PropTypes from 'prop-types';
+import './OptionsPlaceholder.style';
+
+class OptionsPlaceholder extends Component {
+    render() {
+        const { amount } = this.props;
+
+        return (
+            <div block="OptionsPlaceholder">
```
[the remark this answers is not in the document]
Comment (xapiksw) [reply src/app/component/OptionsPlaceholder/OptionsPlaceholder.component.js]: This one is used in both CategoryShoppingOptions and PConfigurableAttributes , and is used for showing placeholders while loading is happening. We cannot fake it in AttributeValue as we don't know ahead how many of them will be there and actually AttributeValue is created only when there is data already available. For PDP the one in CategoryShoppingOptions is OK, but for PLP we have to render more placeholders. thus this component were abstracted here

File: src/app/component/OptionsPlaceholder/OptionsPlaceholder.component.js [hunk 36]
```diff
@@ -0,0 +1,38 @@
...
+                    // eslint-disable-next-line react/no-array-index-key
+                    <div block="OptionsPlaceholder" elem="Option" key={ i } />
+                )) }
+            </div>
+        );
+    }
+}
+
+OptionsPlaceholder.propTypes = {
+    amount: PropTypes.number
```
[the remark this answers is not in the document]
Comment (xapiksw) [reply src/app/component/OptionsPlaceholder/OptionsPlaceholder.component.js]: what for?

File: src/app/component/CartItem/CartItem.component.js (hunk 25 above)
[the remark this answers is not in the document]
Comment (andreas-ateles) [reply src/app/component/CartItem/CartItem.component.js]: But what if the removal call fails (for whatever reason)? If the item is still there then could do it in `.catch(...)`/`.then(null, ...)`.

[the remark this answers is not in the document]
Comment (xapiksw) [reply src/app/component/CartItem/CartItem.component.js]: Thanks for mentioning, for now it seems that it can happen only due to some unhandled error (i.e. that causes error in request). In that case error message from outside component should be shown. Restoring dangerous item from loading state seem too risky in that scenario. However in positive scenario (successful item removal) garbage collection won't work properly as references to callbacks will be from component that does not already exists.
