### PR TITLE
#1638 Fix

### LINKED ISSUE #1638: Cookie popup is missing on Store B, if user agreed with it on another store
**Description**:
Cookie popup is missing on Store B if user agreed with it on another store

**Expected behavior**:
Cookie popup is displayed on store B

**To Reproduce**:
1. Open Store A
2. Tap 'Agree' on the cookie popup
3. Open Store B

**Actual result**:
Cookie popup is missing on Store B

**Notes**:
For example, we have stores for different countries -> maybe these have different T&C/Privacy Policy
Please, show cookie popup for store B too

### PR DESCRIPTION
**Pull request by teodormoq**
#1638

### CODE REVIEW

File: src/app/component/CookiePopup/CookiePopup.component.js [hunk 1]
```diff
@@ -25,18 +25,22 @@ import './CookiePopup.style';
...
 
-    state = { isAccepted: BrowserDatabase.getItem(COOKIE_POPUP) || false };
+    // eslint-disable-next-line react/destructuring-assignment
+    state = { isAccepted: BrowserDatabase.getItem(`${COOKIE_POPUP}_${this.props.code}`) || false };
 
     acceptCookies = () => {
-        BrowserDatabase.setItem(true, COOKIE_POPUP, ONE_MONTH_IN_SECONDS);
+        const { code } = this.props;
+
+        BrowserDatabase.setItem(true, `${COOKIE_POPUP}_${code}`, ONE_MONTH_IN_SECONDS);
```
Comment (yeegor) [inline src/app/component/CookiePopup/CookiePopup.component.js:43]: Consider unifying this logic - the same thing is written in two different ways in one component :(

**Review by yeegor — CHANGES_REQUESTED** [review]

**Review by yeegor — APPROVED** [review]
Seems legit!
