### PR TITLE
[#903] "Write a review" button clips through the navigation menu

### LINKED ISSUE #903: "Write a review" button clips through the navigation menu
**Description**:
Pressing product review button expands the page and clips the "Write a review" button through the navigation menu

**Expected behavior**:

Pressing the "Product reviews" button the page should scroll down to the "Write a review" button as it expands the page.

**Screenshots, Video, Logs**

image

image

**To Reproduce**:

1. Open ScandiPWA demo on mobile
2. Go to any product page
3.Press the "Product reviews" button
4.Observe

**Additional context**:

Tested on Chrome, Firefox, Opera.

### PR DESCRIPTION
**Pull request by MaksimGritcenko**
fixes #903

### CODE REVIEW

File: src/app/component/ExpandableContent/ExpandableContent.component.js [hunk 1]
```diff
@@ -66,11 +68,45 @@ export class ExpandableContent extends PureComponent {
...
+
     toggleExpand = () => {
         const { onClick } = this.props;
+        const { isContentExpanded } = this.state;
+
         if (onClick) {
             onClick(); return;
         }
+
+        this.scrollToExpandedContent(
```
Comment (yeegor) [inline src/app/component/ExpandableContent/ExpandableContent.component.js:106]: I believe these arguments are not necessary here, due to all of them being retrieved from `this`

File: src/app/component/ExpandableContent/ExpandableContent.component.js [hunk 2]
```diff
@@ -66,11 +68,45 @@ export class ExpandableContent extends PureComponent {
         return null;
     }
 
+    scrollToExpandedContent(elementToScrollRef, isContentExpanded, coveringElementsIds) {
+        const elem = elementToScrollRef && elementToScrollRef.current;
+
+        requestAnimationFrame(() => {
+            if (!isContentExpanded && elem) {
```
Comment (yeegor) [inline src/app/component/ExpandableContent/ExpandableContent.component.js:75]: Consider inverting the `if` logic here to reduce nested code amount.

File: src/app/component/NavigationTabs/NavigationTabs.component.js [hunk 3]
```diff
@@ -157,7 +157,8 @@ export class NavigationTabs extends NavigationAbstract {
 
         return (
             <footer block="NavigationTabs" mods={ { isHidden } }>
-                <nav block="NavigationTabs" elem="Nav">
+                { /** Id is required to measure the element`s height in ExpandableContent.component.js */ }
+                <nav id="navigation-tabs" block="NavigationTabs" elem="Nav">
```
Comment (yeegor) [inline src/app/component/NavigationTabs/NavigationTabs.component.js:161]: Please make this ID match our class naming style, e.g. NavigationTabs

File: src/app/component/ProductActions/ProductActions.component.js [hunk 4]
```diff
@@ -545,7 +545,12 @@ export class ProductActions extends PureComponent {
             <article block="ProductActions">
                 { this.renderPriceWithGlobalSchema() }
                 { this.renderShortDescription() }
-                <div block="ProductActions" elem="AddToCartWrapper">
+                <div
+                  // Id is required to measure the element`s height in Component/ExpandableContent.component.js
+                  id="product-actions-wrapper"
```
Comment (yeegor) [inline src/app/component/ProductActions/ProductActions.component.js:550]: Same issue with ID here

**Review by yeegor — CHANGES_REQUESTED** [review]

**Review by yeegor — APPROVED** [review]
