### PR TITLE
SWPWA-555 - fix for menu and customer account buttons not working

### LINKED ISSUE #662: Customer backend buttons not working
2.3.5 M2 with all latest ScandiPWA modules per 29/05/2020.

Description:
Buttons in customer backend not working. No console output as well. (adding address to address book, edit details etc.)
Expected result:
Customer backend section to work. Being able to add an address, edit details, wishlist etc)
afbeelding

### PR DESCRIPTION
**Pull request by AivarsA**
Fixes #662 and #665

### CODE REVIEW

File: src/app/component/Header/Header.container.js [hunk 1]
```diff
@@ -359,7 +360,10 @@ export class HeaderContainer extends NavigationAbstractContainer {
             navigationState: { name }
         } = this.props;
 
-        if (isMobile.any() || name === CART_OVERLAY || (!isMobile.any() && name === SEARCH)) {
+        if (isMobile.any()
```
Comment (yeegor) [inline src/app/component/Header/Header.container.js:363]: Please use concise language :')

Comment (alfredsgenkins) [reply src/app/component/Header/Header.container.js:363]: Please fix that manually, otherwise, it will show-up in every PR :)
